import os
"""
Actions and Builders for gene calling pipeline.
-------------------------------------------------------------------------------
Ian Rambo
Last updated: 2018-12-10
Thirteen... that's a mighty unlucky number... for somebody!
"""

Import('pipeline_env')
gene_env = Environment()
#------------------------------------------------------------------------------
progs = ['prodigal','hmmsearch','jackhmmer']
#Dictionary of output directories
outdirs = {}
for p in progs:
    outdirs[p] = os.path.join(pipeline_env['OUTROOT'], 'gene/%s' % p)

#Add output directories to the gene analysis environment
gene_env.Replace(PRODIGAL=outdirs['prodigal'],
HMMSEARCH=outdirs['hmmsearch'],
JACKHMMER=outdirs['jackhmmer'])
#------------------------------------------------------------------------------
#Prodigal options and Builder
prodigal_opts = {'-i':pipeline_env['FASTA'], '-p':'single',
'-o':os.path.join(gene_env['PRODIGAL'], '%s_prodigal.gff' % pipeline_env['FASTAID']),
'-a':os.path.join(gene_env['PRODIGAL'], '%s_prodigal.faa' % pipeline_env['FASTAID']),
'-f':'gff'}

gene_env.Replace(PRODIGALOPTS=prodigal_opts)

prodigal_action = 'prodigal -q -p %s -f %s -i $SOURCES -o ${TARGETS[0]} -a ${TARGETS[1]}' % (gene_env['PRODIGALOPTS']['-p'], gene_env['PRODIGALOPTS']['-f'])
prodigal_build = Builder(action = prodigal_action)
#------------------------------------------------------------------------------
builders = {'Prodigal':prodigal_build}
#------------------------------------------------------------------------------
gene_env.Append(BUILDERS=builders)
Export('gene_env')

SConscript(['prodigal/SConscript', 'hmmsearch/SConscript', 'jackhmmer/SConscript'])
