"""
Ian Rambo
Build a BLAST database of CRISPR repeats.
"""
import os
import PROGRAM_OPTIONS
Import('database_env')
#==============================================================================
#Download CRISPR repeat database
#crispr_repeat_db = os.path.join(database_env['CRISPR_REP'], 'DRCRISPR.fna')

##Add into GitHub or reference data - what if the link goes down?
#Command(crispr_repeat_db, None, 'wget http://crispr.i2bc.paris-saclay.fr/crispr/BLAST/DR/DRdatabase -O $TARGET')
#------------------------------------------------------------------------------
#Build the BLAST+ database
blastdb_targets = [database_env['CRISPRDB'] + suffix for suffix in ['.nhr', '.nin', '.nsq']]

# for b in blastdb_targets:
#         DEFAULT_TARGETS.append(b)

Command(blastdb_targets, database_env['CRISPRDB'], 'makeblastdb -in $SOURCE -input_type fasta -dbtype nucl')

#crispr_db_symlink = os.path.join(database_env['SRCDIR'], 'DRCRISPR.fna')
#database_env.Command(crispr_db_symlink, crispr_repeat_db, PROGRAM_OPTIONS.symbolic_link)
