import os
"""
Build a BLAST database of CRISPR repeats.
"""
#Download CRISPR repeat database
crispr_repeat_db = os.path.join(database_env['CRISPR_REP'], 'DRCRISPR.fna')
Command(crispr_repeat_db, None, 'wget http://crispr.i2bc.paris-saclay.fr/crispr/BLAST/DR/DRdatabase -O $TARGET')

#Build the BLAST+ database
blastdb_targets = [crispr_repeat_db + suffix for suffix in ['.nhr', '.nin', '.nsq']]

for b in blastdb_targets:
        DEFAULT_TARGETS.append(b)

Progress('Evaluating $TARGET\n')
Command(blastdb_targets, crispr_repeat_db, 'makeblastdb -in $SOURCE -input_type fasta -dbtype nucl')

database_env.Replace(CRISPRDB = crispr_repeat_db)
