"""
Actions and Builders for CRISPR-Cas search pipeline.
Initiate environment for gene annotation portion of CRISPR-Cas search pipeline.
-------------------------------------------------------------------------------
Ian Rambo
Thirteen... that's a mighty unlucky number... for somebody!
"""

Import('pipeline_env')
gene_env = pipeline_env.Clone()
#------------------------------------------------------------------------------
Export('gene_env')

SConscript(['prodigal/SConscript', 'hmmsearch/SConscript', 'jackhmmer/SConscript'], exports = 'gene_env')
